env:
  global:
    - VERSION=0.${TRAVIS_BUILD_NUMBER}
    - DOCKER_HUB_USER=vfarcic

sudo: required

services:
  - docker

before_install:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_62b14f38a520_key -iv $encrypted_62b14f38a520_iv -in proxy-key.enc -out proxy-key -d; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then chmod 600 proxy-key; fi'

script:
  - set -e
  - docker swarm init
  - docker-compose -f docker-compose-test.yml run --rm unit
  - docker build -t vfarcic/docker-flow-cron .
  - docker tag vfarcic/docker-flow-cron vfarcic/docker-flow-cron:${VERSION}
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-cron:${VERSION}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-cron; fi'
  - docker-compose -f docker-compose-test.yml run --rm docs
  - docker build -t vfarcic/docker-flow-cron-docs -f Dockerfile.test .
  - docker tag vfarcic/docker-flow-cron-docs vfarcic/docker-flow-cron-docs:${VERSION}
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-cron-docs:${VERSION}; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push vfarcic/docker-flow-cron-docs; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ssh -o "StrictHostKeyChecking no" -i proxy-key root@${SWARM_MANAGER_1_PUBLIC_IP} docker service update --image vfarcic/docker-flow-cron-docs:${VERSION} cron-docs; fi'

branches:
  only:
    - master
